export const DD_COUNTRY = [
  { value: "AD", text: "Andorra" },
  { value: "AE", text: "United Arab Emirates" },
  { value: "AF", text: "Afghanistan" },
  { value: "AG", text: "Antigua and Barbuda" },
  { value: "AI", text: "Anguilla" },
  { value: "AL", text: "Albania" },
  { value: "AM", text: "Armenia" },
  { value: "AN", text: "Netherlands Antilles" },
  { value: "AO", text: "Angola" },
  { value: "AR", text: "Argentina" },
  { value: "AT", text: "Austria" },
  { value: "AU", text: "Australia" },
  { value: "AW", text: "Aruba" },
  { value: "AZ", text: "Azerbaijan" },
  { value: "BA", text: "Bosnia and Herzegovina" },
  { value: "BB", text: "Barbados" },
  { value: "BD", text: "Bangladesh" },
  { value: "BE", text: "Belgium" },
  { value: "BF", text: "Burkina Faso" },
  { value: "BG", text: "Bulgaria" },
  { value: "BH", text: "Bahrain" },
  { value: "BI", text: "Burundi" },
  { value: "BJ", text: "Benin" },
  { value: "BM", text: "Bermuda" },
  { value: "BN", text: "Brunei Darussalam" },
  { value: "BO", text: "Bolivia" },
  { value: "BR", text: "Brazil" },
  { value: "BS", text: "Bahamas" },
  { value: "BT", text: "Bhutan" },
  { value: "BV", text: "Bouvet Island" },
  { value: "BW", text: "Botswana" },
  { value: "BX", text: "benelux" },
  { value: "BY", text: "Belarus" },
  { value: "BZ", text: "Belize" },
  { value: "CA", text: "Canada" },
  { value: "CF", text: "Central African Republic" },
  { value: "CH", text: "Switzerland" },
  { value: "CI", text: "Côte d'Ivoire" },
  { value: "CK", text: "Cook Islands" },
  { value: "CL", text: "Chile" },
  { value: "CM", text: "Cameroon" },
  { value: "CN", text: "China" },
  { value: "CO", text: "Colombia" },
  { value: "CR", text: "Costa Rica" },
  { value: "CU", text: "Cuba" },
  { value: "CV", text: "Cape Verde" },
  { value: "CY", text: "Cyprus" },
  { value: "CZ", text: "Czech Republic" },
  { value: "DE", text: "Germany" },
  { value: "DJ", text: "Djibouti" },
];
