export const DD_QUANTITY = [
  { type: "WAREHOUSE", value: "B5", text: "BILLET" },
  { type: "WAREHOUSE", value: "BA", text: "BARREL" },
  { type: "VARIOUS", value: "BC", text: "BASIC CARTON" },
  { type: "WAREHOUSE", value: "BG", text: "BAG" },
  { type: "WAREHOUSE", value: "BL", text: "BALE" },
  { type: "WAREHOUSE", value: "BN", text: "BULK" },
  { type: "WAREHOUSE", value: "BO", text: "BOTTLE" },
  { type: "WAREHOUSE", value: "BT", text: "BULK TANK" },
  { type: "WAREHOUSE", value: "BX", text: "BOX" },
  { type: "VOLUME", value: "C8", text: "CUBIC DECIMETRE" },
  { type: "WAREHOUSE", value: "CA", text: "CAN" },
  { type: "VOLUME", value: "CC", text: "CUBIC CENTIMETRE" },
  { type: "VOLUME", value: "CF", text: "CUBIC FOOT" },
  { type: "WAREHOUSE", value: "CH", text: "CONTAINER" },
  { type: "WEIGHT", value: "CK", text: "QUINTAL" },
  { type: "CAPACITY", value: "CL", text: "CENTILITRE" },
  { type: "LENGTH", value: "CM", text: "CENTIMETRE" },
  { type: "WAREHOUSE", value: "CR", text: "CRATE" },
  { type: "WAREHOUSE", value: "CS", text: "CASE" },
  { type: "WAREHOUSE", value: "CT", text: "CARTON" },
  { type: "VOLUME", value: "CU", text: "CUBIC METRE", tip: "M3" },
  { type: "WEIGHT", value: "CW", text: "HUNDREDWEIGHT" },
  { type: "VOLUME", value: "CY", text: "CUBIC YARD" },
  { type: "AREA", value: "D3", text: "SQUARE DECIMETRE" },
  { type: "LENGTH", value: "DK", text: "DECAMETRE" },
  { type: "CAPACITY", value: "DL", text: "DECALITRE" },
  { type: "LENGTH", value: "DM", text: "DECIMETRE" },
  { type: "VARIOUS", value: "DP", text: "DOZEN PAIRS" },
  { type: "VARIOUS", value: "DR", text: "DOZEN ROLL" },
  { type: "VARIOUS", value: "DU", text: "DRUMS" },
  { type: "VARIOUS", value: "DZ", text: "DOZEN" },
  { type: "LENGTH", value: "FT", text: "FOOT" },
  { type: "WEIGHT", value: "G", text: "GRAM" },
  { type: "CAPACITY", value: "GA", text: "U.S. GALLON" },
  { type: "VARIOUS", value: "GB", text: "GROSS BOXES" },
  { type: "CAPACITY", value: "GI", text: "GALLON" },
  { type: "VARIOUS", value: "GS", text: "GROSS" },
  { type: "WEIGHT", value: "HG", text: "HECTOGRAM" },
  { type: "CAPACITY", value: "HL", text: "HECTOLITRE" },
  { type: "LENGTH", value: "HM", text: "HECTOMETRE" },
  { type: "OTHERS", value: "HU", text: "HUNDRED" },
  { type: "LENGTH", value: "IN", text: "INCH" },
  { type: "VARIOUS", value: "IU", text: "INTERNATIONAL UNIT" },
  { type: "WEIGHT", value: "KG", text: "KILOGRAM", tip: "KG" },
  { type: "CAPACITY", value: "KL", text: "KILOLITRE" },
  { type: "LENGTH", value: "KM", text: "KILOMETRE" },
  { type: "CAPACITY", value: "L", text: "LITRE" },
  { type: "VARIOUS", value: "LA", text: "LITRE ALCOHOL" },
  { type: "WEIGHT", value: "LB", text: "POUND" },
  { type: "WEIGHT", value: "LT", text: "POUND TROY" },
];
